services:
  posters_db:
    image: mongo:4.4
    container_name: mongodb-poster
    environment:
      MONGO_INITDB_DATABASE: posters_db
    volumes:
      - ./data_db:/data/db
      - ./src/main/resources/mongo/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "10079:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-poster:
    image: gitlab-depinfo.univ-brest.fr:5050/e22200893/apis/api-poster:v1.0.0
    ports:
      - "10064:8080"
    depends_on:
      posters_db:
        condition: service_healthy
    environment:
      MONGO_HOST: posters_db
      MONGO_PORT: 27017
      MONGO_DB: posters_db

volumes: {}